apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    volume: postgres-database
  name: postgres-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
